Repository sham-a/prescribed, pull requests merged in 2021-04, with the labels that each got.

#9 Profile and nav page
  prescribed/app/build.gradle
  prescribed/app/src/main/AndroidManifest.xml
  prescribed/app/src/main/ic_launcher-playstore.png
  prescribed/app/src/main/java/com/example/prescribed/AppointmentFragment.java
  prescribed/app/src/main/java/com/example/prescribed/ChatFragment.java
  prescribed/app/src/main/java/com/example/prescribed/FAQFragment.java
  prescribed/app/src/main/java/com/example/prescribed/MainActivity.java
  prescribed/app/src/main/java/com/example/prescribed/MedicationActivity.java
  prescribed/app/src/main/java/com/example/prescribed/ProfileFragment.java
  prescribed/app/src/main/java/com/example/prescribed/chat/ChatActivity.java
  prescribed/app/src/main/java/com/example/prescribed/ui/login/LoginActivity.java
  prescribed/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  prescribed/app/src/main/res/drawable/ic_add.xml
  prescribed/app/src/main/res/drawable/ic_arrow_right.xml
  prescribed/app/src/main/res/drawable/ic_badge.xml
  prescribed/app/src/main/res/drawable/ic_launcher_foreground.xml
  prescribed/app/src/main/res/drawable/ic_question_answer.xml
  prescribed/app/src/main/res/drawable/ic_schedule.xml
  prescribed/app/src/main/res/drawable/ic_settings.xml
  prescribed/app/src/main/res/drawable/ic_textsms.xml
  prescribed/app/src/main/res/layout/activity_login.xml
  prescribed/app/src/main/res/layout/activity_main.xml
  prescribed/app/src/main/res/layout/activity_medications.xml
  prescribed/app/src/main/res/layout/fragment_appointment.xml
  prescribed/app/src/main/res/layout/fragment_chat.xml
  prescribed/app/src/main/res/layout/fragment_f_a_q.xml
  prescribed/app/src/main/res/layout/fragment_profile.xml
  prescribed/app/src/main/res/menu/bottom_menu.xml
  prescribed/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  prescribed/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  prescribed/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  prescribed/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  prescribed/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  prescribed/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  prescribed/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  prescribed/app/src/main/res/navigation/my_nav.xml
  prescribed/app/src/main/res/values-round/strings.xml
  prescribed/app/src/main/res/values/arrays.xml
  prescribed/app/src/main/res/values/dimens.xml
  prescribed/app/src/main/res/values/ic_launcher_background.xml
  prescribed/app/src/main/res/values/strings.xml
  prescribed/app/src/main/res/xml/root_preferences.xml
Labels: enhancement

#10 Add med
  prescribed/app/build.gradle
  prescribed/app/src/main/AndroidManifest.xml
  prescribed/app/src/main/java/com/example/prescribed/addMed/AddMedActivity.java
  prescribed/app/src/main/java/com/example/prescribed/ui/login/LoginActivity.java
  prescribed/app/src/main/res/drawable-xhdpi/green_mic.png
  prescribed/app/src/main/res/drawable-xhdpi/green_mic_better.png
  prescribed/app/src/main/res/layout/enter_med_freq.xml
  prescribed/app/src/main/res/layout/enter_med_name.xml
  prescribed/app/src/main/res/layout/enter_med_notes.xml
  prescribed/app/src/main/res/layout/enter_med_start.xml
  prescribed/app/src/main/res/values/strings.xml
  prescribed/app/src/main/res/xml/root_preferences.xml
  prescribed/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#11 Bug fix and connect
  prescribed/app/src/main/java/com/example/prescribed/MainActivity.java
  prescribed/app/src/main/res/drawable/ic_mic_black.xml
  prescribed/app/src/main/res/drawable/ic_mic_blue.xml
  prescribed/app/src/main/res/layout/fragment_profile.xml
  prescribed/app/src/main/res/mipmap-hdpi/ic_launcher.png
  prescribed/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  prescribed/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  prescribed/app/src/main/res/mipmap-mdpi/ic_launcher.png
  prescribed/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  prescribed/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  prescribed/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  prescribed/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  prescribed/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  prescribed/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  prescribed/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  prescribed/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  prescribed/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  prescribed/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  prescribed/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: enhancement

#14 Finishing speech rec
  prescribed/app/src/main/AndroidManifest.xml
  prescribed/app/src/main/java/com/example/prescribed/addMed/AddMedActivity.java
  prescribed/app/src/main/java/com/example/prescribed/addMed/Frequency.java
  prescribed/app/src/main/java/com/example/prescribed/addMed/Medication.java
  prescribed/app/src/main/java/com/example/prescribed/addMed/medRecord.java
  prescribed/app/src/main/res/drawable/ic_mic_black.xml
  prescribed/app/src/main/res/drawable/ic_mic_blue.xml
  prescribed/app/src/main/res/layout/enter_med_name.xml
  prescribed/app/src/main/res/layout/enter_med_notes.xml
  prescribed/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  prescribed/app/src/main/res/values-night/themes.xml
  prescribed/app/src/main/res/values/colors.xml
  prescribed/app/src/main/res/values/themes.xml
Labels: bug, enhancement

#15 Final touches
  prescribed/app/build.gradle
  prescribed/app/src/main/AndroidManifest.xml
  prescribed/app/src/main/java/com/example/prescribed/MainActivity.java
  prescribed/app/src/main/java/com/example/prescribed/MedicationActivity.java
  prescribed/app/src/main/java/com/example/prescribed/RecyclerViewAdapter.java
  prescribed/app/src/main/java/com/example/prescribed/addMed/medRecord.java
  prescribed/app/src/main/res/drawable/ic_camera.xml
  prescribed/app/src/main/res/drawable/med_border.xml
  prescribed/app/src/main/res/layout/activity_login.xml
  prescribed/app/src/main/res/layout/activity_medications.xml
  prescribed/app/src/main/res/layout/enter_med_freq.xml
  prescribed/app/src/main/res/layout/enter_med_name.xml
  prescribed/app/src/main/res/layout/enter_med_notes.xml
  prescribed/app/src/main/res/layout/enter_med_start.xml
  prescribed/app/src/main/res/layout/fragment_appointment.xml
  prescribed/app/src/main/res/layout/fragment_chat.xml
  prescribed/app/src/main/res/layout/fragment_f_a_q.xml
  prescribed/app/src/main/res/layout/fragment_profile.xml
  prescribed/app/src/main/res/layout/layout_listmedications.xml
  prescribed/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  prescribed/app/src/main/res/values/colors.xml
  prescribed/app/src/main/res/values/ic_launcher_background.xml
Labels: enhancement

#16 fixed the 24h wrap around
  prescribed/app/src/main/java/com/example/prescribed/addMed/medRecord.java
Labels: bug
